# Compose: docker compose --file=./apps/notification/docker-compose.dev.yml --project-name "readme-notification" --env-file=./apps/notification/notification.env up -d
# curl smtp://localhost:8025 --mail-from iron-man@stark-industries.ai --mail-rcpt ai@jarvis.local --upload-file ./email.txt
version: '3.9'
services:
  readme.notification.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: "readme.notification.fakesmtp"
    hostname: "readme.notification.fakesmtp"
    ports:
      - ${FAKE_SMTP_SERVER_PORT}:8025
      - ${FAKE_SMTP_UI_PORT}:8080
