# Server settings
@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api

# Environment
@userId = 5a614a31-92c9-48da-9551-f09548184234

GET {{baseUrl}}/users/{{userId}}
###

PATCH {{baseUrl}}/users/password/{{userId}}
Content-Type: application/json

{
  "password": "test-password123",
  "newPassword": "123456"
}
###
