# Server settings
@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api
# Environment
@userId = 663fa14c55082f2d17c3ee70

# Get detail info about user
GET {{baseUrl}}/users/{{userId}} HTTP/1.1
###

# Update user info
PATCH  {{baseUrl}}/users/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "firstName": "TT"
}
###

# Delete user
DELETE {{baseUrl}}/users/{{userId}} HTTP/1.1
###

# Change user password
PATCH {{baseUrl}}/users/{{userId}}/password/ HTTP/1.1
Content-Type: application/json

{
  "password": "jarvis-123",
  "newPassword": "123456"
}
###
