@host = 127.0.0.1
@port = 9000
@baseUrl = http://{{host}}:{{port}}/api/{{postId}}/comments/
#Test Request to JSON Placeholder
GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
Content-Type: application/json
###

@postId = abdb5908-7ac4-467e-ab2a-76d11a5feeaf
@commentId = b3c1fd04-d867-4b96-9cbe-7cc9b7783a90

# Create comment for post
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
  "authorId": "662253e794534cbee6562f7d",
  "text": "Some new comment"
}
###

# Update comment
PATCH  {{baseUrl}}/posts/{{commentId}} HTTP/1.1
Content-Type: application/json

{
  "authorId": "662253e794534cbee6562f7d",
  "text": "Test comment2"
}
###

# Delete comment
DELETE  {{baseUrl}}/posts/{{commentId}} HTTP/1.1
Content-Type: application/json
###
