# Server settings
@host = 127.0.0.1
@port = 9000
# @port = ${{ $processEnv PORT }}
@baseUrl = http://{{host}}:{{port}}/api

# Environment
@userId = 6dd03634-9785-49b8-a403-9ab61bb5656e
@postId = 6c9b872e-2716-45a6-9377-ffdf594eae40

# Create post
POST {{baseUrl}}/posts HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "tags": ["test1", "test2", "news"],
  "isPublished": true,
  "isRepost": false,
  "authorId": "6dd03634978549b8",
  "originAuthorId": "",
  "originPostId": "",
  "extraFields": {
    "announce": "Some announce text",
    "title": "Article title",
    "text": "Long story short text"
  }
}
###

# Find post by id
GET {{baseUrl}}/posts/{{postId}} HTTP/1.1
Content-Type: application/json
###
