# Server settings
@host = 127.0.0.1
@port = 9000
@baseUrl = http://{{host}}:{{port}}/api

# Environment
@userId = 6dd03634-9785-49b8-a403-9ab61bb5656e

# Create post
POST {{baseUrl}}/posts HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "tags": ["3dd59389-d3c9-4203-8e20-d7f29431cdaa"],
  "isPublished": true,
  "isRepost": false,
  "authorId": "6dd03634978549b8",
  "originAuthorId": "",
  "originPostId": "",
  "extraFields": {
    "announce": "Some announce text",
    "title": "Article title",
    "text": "Long story short text"
  }
}
