@host = 127.0.0.1
@port = 9000
@baseUrl = http://{{host}}:{{port}}/api
#Test Request to JSON Placeholder
GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
Content-Type: application/json
###

@postId = d2d101a7-d73d-4ffc-9bf0-7eb1589e52a0
@likeId = 57f40cb3-f074-428b-906c-1e719c9fb96d
@authorId = 662253e794534cbee6562f7d

# Toggle Like
POST {{baseUrl}}/posts/{{postId}}/likes HTTP/1.1
Content-Type: application/json

{
  "authorId": "662253e794534cbee6562f7d"
}
###

# Get Likes by post id
GET {{baseUrl}}/posts/{{postId}}/likes HTTP/1.1
Content-Type: application/json
###

# Get Likes by author id
GET {{baseUrl}}/posts/{{postId}}/likes/{{authorId}} HTTP/1.1
Content-Type: application/json
###
